"""initial schema: users, items

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-18

Hand-written rather than autogenerated so every statement is deliberate.
Autogenerate is safe to use for migration 0002 onward, once there's an
existing schema for it to diff against.
"""

import sqlalchemy as sa

from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("hashed_password", sa.String(128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # Unique index rather than a plain one: it enforces the constraint AND
    # serves the login lookup, so email=? is a single index hit.
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "owner_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # Every items query filters by owner_id, so without this index the list
    # endpoint degrades into a full table scan as the table grows.
    op.create_index("ix_items_owner_id", "items", ["owner_id"])


def downgrade() -> None:
    # Reverse creation order so foreign keys never block a drop.
    op.drop_index("ix_items_owner_id", table_name="items")
    op.drop_table("items")

    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
